### ISSUE TITLE
crashing when tryng to open inventory in creative mode

### ISSUE THREAD

**Issue by lightning02** [delvr/Farseek#7]
[crash-2015-12-16_00.23.41-client.txt](https://github.com/delvr/Farseek/files/64567/crash-2015-12-16_00.23.41-client.txt)

**Comment by delvr** [comment]
This looks like a Streams/ThermalDynamics bug that was fixed in Streams 1.0.5 (I see you're using 1.0.4). Try upgrading to the latest version of Streams and let me know if this happens again.

**Comment by lightning02** [comment]
aww, thanks for the kind! it seems more stable, but for example when I use the guy scrolling down some pages like chisel2 for example it keep crashing, is still a stream conflict?
[crash-2015-12-17_11.09.44-client.txt](https://github.com/delvr/Farseek/files/65848/crash-2015-12-17_11.09.44-client.txt)

anyway, tha page looks still empty even if it stopped crashing, is this in the screen a serious problem? should I contact again the thermal dynamics devs?
![12380832_10208464373270923_1561128215_o](https://cloud.githubusercontent.com/assets/11884147/11879780/aa9abcf6-a4fd-11e5-8d93-f44c73a4c628.jpg)

**Comment by delvr** [comment]
This new crash doesn't seem related to Streams or Farseek. Googling your error message ("Already tesselating") suggests a conflict between Optifine and various mods which some people have fixed by adjusting Optifine settings or removing it entirely.

If you still suspect Streams/Farseek, try removing these two mods and see if it still happens. Make sure to use a backup of your save for this, since removing Streams will mess up any existing rivers.

**Comment by lightning02** [comment]
Thanks in advance for your availability, for the last problem it is not your mod not even optifine nor Thermal Dynamics (tryed to remove both and the crash persist).
is better if I use v 0.1.5 or 0.1.6 of your mod? which one is more stable?

**Comment by lightning02** [comment]
it seem solvel now.. the problem was the Chisel 2. Really thanks for your patience!!!

**Comment by delvr** [comment]
Glad to hear it!
